# Generated by Django 4.1 on 2022-08-10 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Enter Your name'}, max_length=264)),
                ('username', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=264)),
                ('role', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Enter Your name'}, max_length=264)),
                ('username', models.CharField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
