# Generated by Django 4.1 on 2022-08-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
