# Generated by Django 4.1 on 2022-08-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
